- index.html
Download URL pointed to the display version (also linked above).
Corrected to point to the Github repo.
> Download URL was wrong

- visual-style.html
Reverts wikimedia/WikimediaUI-Style-Guide#12
The HTML includes control characters. Also please try to follow https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines for your commit messages.
> Revert "Change accent colors image example to html"

- visual-style.html
Aligning heading structure to other “Visual Style” sub-pages as it
is more harmonious and doesn't mislead “Principles” as overview page.
Bug: T162487
> layout: Align heading structure to other “Visual Style” sub-pages

- visual-style_typography.html
Presenting Charter as the generic typefaces and making it clear we
recommend Charis as the preferred implementation.
> Clarifying the Charter/Charis relationship

- package.json
autoprefixer               ^7.2.5  →   8.0.0
grunt                       1.0.1  →   1.0.2
postcss-custom-properties  ^6.2.0  →   7.0.0
stylelint                   8.2.0  →   9.1.1
Also removing inconsistently used caret range. We do this manually to
be fully sure not to break anything.
Also putting “dependencies” before “devDependencies”.
> build: Update devDependencies to latest

- CONTRIBUTING.md
Replacing `npm run build` with current `npm run start`.
> Fix outdated npm command

- index.html
Simplifying and strengthening “Introduction” section by separating
concerns and clearer addressing audiences' needs.
Moving most of contributing out into CONTRIBUTING.md in a next step.
Bug: [T180520](https://phabricator.wikimedia.org/T180520)
> content: Simplify and strengthen “Introduction”

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
`rel="noopener"` prevents pages from abusing window.opener, see
https://mathiasbynens.github.io/rel-noopener/
Bug: [T188698](https://phabricator.wikimedia.org/T188698)
> content: Add `rel="noopener"` to all `target="_blank" attributed links

- index.html
* We don't use Slack at Wikimedia
* There's no mention of what channel/where/how to join
> Remove Slack reference

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
It used to be wikimediafoundation.org but now it's foundation.wikimedia.org
> Update URL to Wikimedia Foundation website

- visual-style_typography.html
Updating system font stack and removing a.o. `system-ui` as it
would be resulting in unintended side-effects in some OS/language
combinations.
Bug: [T175877](https://phabricator.wikimedia.org/T175877)
> Update system font stack to reflect latest iteration

- resources.html
Fixing 404 on Adobe Illustrator file for icons and amend layout to
two download columns.
> “Resources”: Fix 404 and slightly amend layout

- visual-style_typography.html
Removing 'SFMono-Regular' as it needs to be specifically installed.
It just adds bytes for huge majority of users.
> “Visual Style – Typography”: Amend monospace font stack

- package-lock.json
- package.json
> build: Remove wrongly introduced (global) 'npm-check-updates' dependency

- visual-style_typography.html
Review of Typography section to emphasise system fonts as the primary
choice, keeping platform-neutral options to specific cases.
> More prominence to system fonts

- visual-style_icons.html
Linking to template file and to icon source and SVG files to clarify
icon guidelines and resources availability.
Bug: [T229629](https://phabricator.wikimedia.org/T229629)
> “Visual Style – Icons”: Link template and resources clearer

- visual-style_typography.html
Remove “laws of simplicity” link as it doesn't provide value here and
explanation is already enough. Also fixing small typo.
> “Visual style – Typography”: Remove uninsightful link and fix typo

- components/text-inputs-and-textarea.html
"Text inputs and textarea" section had an "&" character by mistake. This change removes the unnecessary character.
> Unnecessary ampersand removed

- index.html
It isn't the best place to get in contact with the design team
compared to the other points of contact.
Decision made in today's Style Guide meeting.
> Remove IRC link

- components/file-inputs.html
Adding resource hints to exemplary file naming guidelines of Wikimedia projects.
> “Components – File inputs”: Add resources links to file naming guidelines

- img/components/buttons_toggle_intro.svg
- img/components/checkboxes_indeterminate_intro_on.svg
- img/components/checkboxes_states.svg
- img/components/dropdowns_designing.svg
- img/components/dropdowns_states.svg
- img/components/file_inputs_designing.svg
- img/components/file_inputs_intro.svg
- img/components/file_inputs_select_button_only_intro.svg
- img/components/number_inputs_intro.svg
Using fallback `sans-serif` across component images.
> “Components”: Ensure SVG font choice is accurately rendered

- components/buttons.html
- components/links.html
Linking in-between and clarifying “Links” and “Buttons” pages.
> “Components”: Clarify using links and buttons

- components/button-groups.html
- components/buttons.html
- components/checkboxes.html
- components/comboboxes.html
- components/dropdowns.html
- components/file-inputs.html
- components/links.html
- components/messages.html
- components/number-inputs.html
- components/radio-buttons.html
- components/text-inputs-and-textarea.html
- components/toggle-switches.html
- design-principles.html
- design-principles_accessibility.html
- index.html
- resources.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
I discovered when the "Contribute on GitHub" button is clicked, it just loads closing up the file the individual was actually reading which is not suppose to be. I added a target property so it opens up a new tab whenever it is clicked, in that case the user can still continue what he/she was doing previously before clicking the button so he/she does not loose track of where he/she was.
> Added a target property

- visual-style_colors.html
On transfer between https://phabricator.wikimedia.org/M82 and
Design Style Guide the label was wrongly set to “Accent10” where
it should be similar to utility colors brightness equivalent colors.
Bug: (T249148)[https://phabricator.wikimedia.org/T249148]
> Fix Accent30 label

- Gruntfile.js
Binary images have been recurringly trouble-some in optimization.
> build: Exclude 'principles-paper-ink.svg' from 'svgmin' Grunt task

- resources/WikimediaUI-components_overview-RSS.xml
Latest Sketch file includes among other changes
Base10 amendment.
> “Resources”: Bump RSS to v1.5.0 to cast new Sketch version

- CONTRIBUTING.md
- components/messages.html
- fix: Broken link to inline validation https://phabricator.wikimedia.org/T255944
- docs: Add command for testing as it is referenced in previous line
> “Components”: Fix inline validation link on Messages page

- components/messages.html
Was missing due to search and replace not taking `is-on` class into
account.
> nav: Add missing link

- img/components/dialogs_complex_designing_scrolling.svg
`grunt replace` was missed before commit of this image.
> images: Fix fallback font for exported SVG

- components/buttons.html
- components/dropdowns.html
Clarify why we're not requiring level AA contrast ratio on
(some) disabled components.
> “Components”: Add note on disabled “Buttons”/“Dropdowns” contrast ratio

- .browserslistrc
- package-lock.json
- package.json
Use central, shareable `browserslist-config-wikimedia/basic` config.
Bug: [T282937](https://phabricator.wikimedia.org/T282937)
> build: Add and use 'browserslist-config-wikimedia'

- Gruntfile.js
- package-lock.json
- package.json
Abandoning 'grunt-sketch' with Figma on the brink. Will slowly
provide similar automated export steps to Figma resourcing over time.
For now manual exporting is sufficient.
Bug: [T205666](https://phabricator.wikimedia.org/T205666)
> build: Remove abandoned 'grunt-sketch' package

- resources.html
- visual-style_illustrations.html
Some links to the illustration resources were broken
> “Resources”: Fix illustration building blocks links

- apps/apps.html
Was falsely remaining as uppercase 'Android' while local file was
lowercased.
> “Apps”: Fix image path

- .svgo.config.js
- Gruntfile.js
- package-lock.json
- package.json
Replacing 'grunt-svgmin' with 'svgo' v2.8.0.
Also
- replacing Grunt based task with npm equivalent including excluded
SVG file.
- changing to JS based '.svgo.config.js'
#465
Bug: [T246321](https://phabricator.wikimedia.org/T246321)
Bug: [T278656](https://phabricator.wikimedia.org/T278656)
> build: Replace 'grunt-svgmin' with npm based 'svgo'

- .github/workflows/node.js.yml
Also Node 16 as it's the current minimal version on Wikimedia infrastructure.
> build: Update GitHub workflows to check Node 18
