- package.json
> Fix incorrect version number

- Gruntfile.js
> Fixes "default" grunt task not running cssmin properly

- build/README.md
- build/build.sh
Based on top of #16 (will rebase it once #16 is merged)
> 	Adding a shell script to copy third-party libraries

- visual-style.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
Bug: [T160598](https://phabricator.wikimedia.org/T160598)
> Add missing subpage title in pages' <title> tag

- visual-style_colors.html
> Fix dark red color

- index.html
Simplifying and strenghtening introduction page by
- making diverse audience and its influence on the style guide clearer,
- using action verb form where applicable and
- reducing sentences where applicable
> Simplify and strengthen introduction

- CONTRIBUTING.md
- LICENSE.txt
- README.md
- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
Amending site title for better clarification and putting technical
note at end.
> Amend title for better clarification

- index.html
Improving readability by using simpler terms and sentences,
restructuring order slightly and adding links.
Bug: [T180520](https://phabricator.wikimedia.org/T180520)
> Improve “Introduction” page contents

- visual-style.html
alternative word suggestion, because executions could be misunderstood
> Reword “execution” to “examinations”

- visual-style_icons.html
the link was opening the widgets page
> fix link, add space

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
Bug: [T188786](https://phabricator.wikimedia.org/T188786)
> Add Matomo (former Piwik) analytics script

- index.html
Usage of unordered list seemed arbitrary, especially with a semantic
unordered list following in “How to participate” section below.
Also removing “usability” as it's part of HCI.
> Change “Introduction” process paragraph

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
Bug: [T177812](https://phabricator.wikimedia.org/T177812)
> Add OpenGraph meta tags

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_imagery.html
- visual-style_typography.html
Bug: [T181115](https://phabricator.wikimedia.org/T181115)
> Add privacy policy link to footer

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
Bug: [T177812](https://phabricator.wikimedia.org/T177812)
> Add RDFa tags for Schema.org

- CONTRIBUTING.md
Not sure how but #72 added some repeated content and in HTML
instead of MD.
> CONTRIBUTING: Fix syntax and remove repeating content

- visual-style_images.html
Adding missing whitespace.
Bug: #123
> “Visual style – Images”: Fix typo

- design-principles.html
- index.html
> Add missing `p` tag and remove loose `ul` tag

- visual-style_typography.html
Soften the 75 character limit from rule to guideline and emphasize its language-specific background.
> ”Visual Style – Typography“: Clarify 75 character limit to be primary language-specific

- design-principles.html
- index.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
> Update privacy policy link to non-wiki privacy policy

- Gruntfile.js
- package.json
Adding 'eslint' and 'eslint-config-wikimedia' latest and
applying its code standards.
> build: Add eslint and align to Wikimedia coding standards

- package-lock.json
Updating 'package-lock.json' with latest dependencies (again).
Following-up #161.
> build: Follow-up update dependencies

- visual-style_images.html
Useful resources, brought up by @quiddity-wp in https://phabricator.wikimedia.org/T186027#4063438
> “Visual Style – Images”: Add project-specific resources links

- visual-style_typography.html
> “Visual Style: Typography”: Use '777' as starting number

- visual-style_typography.html
Bug: [T220323](https://phabricator.wikimedia.org/T220323)
> “Visual Style: Typography”: Add third nesting level to unordered lists

- .gitignore
Coming from #200 we need to ignore more widely. Also removed
composer.lock as we don't use composer here.
> Add several elements to .gitignore

- visual-style.html
- visual-style_typography.html
Script was leftover of IE 8 support code remove done in #132.
> Fix markup discrepancies

- design-principles.html
- index.html
- resources.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
Updating to 'https://wikimediafoundation.org/'.
> Update Foundation website links

- resources.html
Bug: [T230199](https://phabricator.wikimedia.org/T230199)
> “Resources”: Add Sketch library as RSS import features

- CONTRIBUTING.md
Bug: [T235013](https://phabricator.wikimedia.org/T235013)
> CONTRIBUTING: Update to reflect Git LFS dependency

- img/design-principles/this-is-for-everyone--mobile.svg
- img/design-principles/this-is-for-everyone.svg
- resources/Wikimedia_Design_Style_Guide-imagery.sketch
Updating Sketch file with original artwork. Also defining file
color profile.
Bug: [T228764](https://phabricator.wikimedia.org/T228764)
> “Design Principles”: Update “This is for everyone” Sketch and mobile

- LICENSE.txt
> Bump copyright year to 2019

- .eslintrc.json
- .stylelintrc
- Gruntfile.js
- css/build/wmui-style-guide.css
- js/src/embed-tracking-code.js
- package-lock.json
- package.json
autoprefixer                 9.6.1  →   9.6.5
eslint-config-wikimedia     0.13.1  →  0.15.0
grunt-stylelint             0.11.0  →  0.12.0
postcss                     7.0.17  →  7.0.18
postcss-custom-properties   8.0.10  →   9.0.2
stylelint-config-wikimedia   0.6.0  →   0.7.0
> build: Update dependencies & devDependencies to latest

- .gitignore
- scap/scap.cfg
- scap/targets
This simply adds a scap/scap.cfg and scap/targets
and ignores /scap/log in .gitignore
> Add wikimedia deployment (scap) configuration

- components/number-inputs.html
- components/text-inputs-and-textarea.html
Also clarify a number of sentences in text inputs and add color
hints to “Placeholder” description.
> “Components”: Add “Number inputs”

- resources/WikimediaUI-icons-SVGs/down.svg
- resources/WikimediaUI-icons-SVGs/up.svg
> “Resources”: Add 'down' & 'up' indicator

- Gruntfile.js
Adding 'replace' to 'images-pre-production' task.
> build: Add 'images-pre-production' Grunt task

- components/checkboxes.html
- components/dropdowns.html
- components/file-inputs.html
- components/links.html
- components/messages.html
- components/number-inputs.html
- components/radio-buttons.html
- components/text-inputs-and-textarea.html
- design-principles.html
- index.html
- resources.html
- robots.txt
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
Also removing block of section in 'robots.txt'.
Bug: [T229333](https://phabricator.wikimedia.org/T229333)
> “Components”: Add section officially by opening navigation item

- CONTRIBUTING.md
- README.md
- index.html
Also updating 'CONTRIBUTING.md' and 'README.md' to be more
friendly and clearer in our message.
> Update starting page welcome message to collaboration

- components/button-groups.html
- components/buttons.html
- components/checkboxes.html
- components/comboboxes.html
- components/dropdowns.html
- components/file-inputs.html
- components/links.html
- components/messages.html
- components/number-inputs.html
- components/radio-buttons.html
- components/text-inputs-and-textarea.html
- components/toggle-switches.html
- design-principles.html
- index.html
- package.json
- resources.html
- visual-style.html
- visual-style_colors.html
- visual-style_icons.html
- visual-style_illustrations.html
- visual-style_images.html
- visual-style_typography.html
Bug: [T240390](https://phabricator.wikimedia.org/T240390)
> Update Twitter handle to `@WikimediaDesign`

- components/checkboxes.html
- components/links.html
Also fix minor markup issue in “Checkboxes”.
> “Components”: Add external references to “Links”

- visual-style_colors.html
Add reference to enwiki's Manual of Style on accessible colors.
> “Visual style – Colors”: Amend resources and add reference

- visual-style_icons.html
Updating to provide clearer language, adding internal and external links
and color hints.
> “Visual style – Icons”: Update page with clearifying language & color hints

- components/button-groups.html
- components/buttons.html
- components/checkboxes.html
- components/comboboxes.html
- components/dropdowns.html
- components/file-inputs.html
- components/links.html
- components/messages.html
- components/number-inputs.html
- components/radio-buttons.html
- components/text-inputs-and-textarea.html
- components/toggle-switches.html
Adding `section` to enable sub-linking to sections like “Types”.
> “Components”: Add `section` element for structuring & direct linking

- index.html
Also move paragraphs to strengthen the narrative and remove
duplicated information in too close distance.
> “Introduction”: Link “Visual style” and “Components”

- design-principles.html
> Show “Accessibility” section in “Design principles” menu

- scap/targets
Bug: (T247650)[https://phabricator.wikimedia.org/T247650]
> build: Update scap-targets from bromine/vega to miscweb1002/2002

- visual-style_illustrations.html
With links to building block files and “Resources” page.
> “Visual style – Illustrations”: Add resources section

- visual-style_typography.html
Adding references to shed a light on historic reasons for choices, which
have influenced current selection as well.
> “Visual style – Typography”: Add historic & font choice background references

- package-lock.json
- package.json
And also grunt from 1.2.1 to 1.3.0, and an `npm audit fix` whilst we're here.
> build: Upgrade eslint-config-wikimedia from 0.16.2 to 0.17.0

- CONTRIBUTING.md
Bug: [T266335](https://phabricator.wikimedia.org/T266335)
> contributing: Add process list on adding and extending components

- components/comboboxes.html
- components/file-inputs.html
- components/messages.html
- components/text-inputs-and-textarea.html
Using singular 'the user' form for all component references to the user.
> “Components”: Use unified language on 'the user'

- components/comboboxes.html
- components/text-inputs-and-textarea.html
Also clarify optional character of autocomplete and dropdown menus for
text inputs.
> “Components”: Unify on correct “autocomplete“ term

- components/buttons.html
- components/checkboxes.html
- components/comboboxes.html
- components/dialogs.html
- components/dropdowns.html
- components/links.html
- components/messages.html
- components/number-inputs.html
- components/radio-buttons.html
- components/text-inputs-and-textarea.html
- components/toggle-switches.html
Also fix missing `</section>` tag on checkboxes file.
> “Components”: Add WikimediaUI theme Figma links to various components

- visual-style_colors.html
Adding link to Figma file for better equitable source of truth.
> “Visual style – Colors”: Add WikimediaUI Icons & Colors Figma file link

- CONTRIBUTING.md
Expanding with most up-to-date information and Phabricator links for
designers.
> contributing: Expand designing and updating icons section
